# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b1c98791a50b100a9c11cbc9c9c523a5"
application_url = "https://badge-assessing-customers-year.trycloudflare.com"
embedded = true
name = "shppify-proxy-test"
handle = "shppify-proxy-test"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://badge-assessing-customers-year.trycloudflare.com/auth/callback",
  "https://badge-assessing-customers-year.trycloudflare.com/auth/shopify/callback",
  "https://badge-assessing-customers-year.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
